{ config, lib, pkgs, dotfiles, ... }:

let
  inherit (lib) mkEnableOption mkOption types mkIf mkDefault;
  cfg = config.programs.illogical-impulse;

  # Используем dotfiles из flake-входа (path:./dotfiles) — без обёртки.
  dotfilesSource = dotfiles;

  # Локальные пакеты (иконки, шрифты). Сюда же вынесен Papirus с исправленным
  # наследованием (патч при сборке, а не sed в activation-скрипте — см. pkgs/).
  customPkgs = import ../pkgs { inherit pkgs; };
in
{
  options.programs.illogical-impulse.dotfiles = {
    fish.enable = mkEnableOption "Use the Illogical Impulse fish config" // { default = true; };
    starship.enable = mkEnableOption "Install starship and use the Illogical Impulse prompt" // { default = true; };
  };

  options.programs.illogical-impulse.hyprland = {
    plugins = mkOption {
      type = types.listOf types.package;
      default = [];
      description = "Hyprland plugins to install and load via hl.plugin()";
    };
  };

  config = mkIf cfg.enable {
    # Shell programs
    programs.fish.enable = cfg.dotfiles.fish.enable;
    # Interactive shell init. NOTE: home-manager's programs.fish generates
    # ~/.config/fish/config.fish (symlinked from the nix store), so the vendored
    # dotfiles/fish/config.fish is NOT loaded. Everything interactive must live here.
    programs.fish.interactiveShellInit = ''
      # No greeting ("Welcome to fish, the friendly interactive shell")
      set -g fish_greeting

      # Use starship (transient prompt)
      function starship_transient_prompt_func
          starship module character
      end
      if test "$TERM" != "linux"
          starship init fish | source
          enable_transience
      end

      # Terminal colors (generated by quickshell wallpaper theming)
      if test -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt
          cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
      end

      # Aliases
      alias clear "printf '\033[2J\033[3J\033[1;1H'"
      alias celar "printf '\033[2J\033[3J\033[1;1H'"
      alias claer "printf '\033[2J\033[3J\033[1;1H'"
      alias pamcan pacman
      alias q 'qs -c ii'
      if test "$TERM" != "linux"
          alias ls 'eza --icons=auto'
      end
    '';
    programs.starship.enable = cfg.dotfiles.starship.enable;

    # Install plugin .so files into the user environment
    home.packages = cfg.hyprland.plugins;

    # Fake venv at the path upstream expects: ~/.local/state/quickshell/.venv
    # The complex shebang in Python scripts does: source $ILLOGICAL_IMPULSE_VIRTUAL_ENV/bin/activate
    # The upstream env.lua sets ILLOGICAL_IMPULSE_VIRTUAL_ENV to this path.
    home.file = {
      # X11 default cursor theme for XWayland apps (Steam, Wine, etc.)
      ".icons/default/index.theme".text = ''
        [Icon Theme]
        Name=Default
        Comment=Default Cursor Theme
        Inherits=Bibata-Modern-Classic
      '';
      ".icons/Bibata-Modern-Classic".source = "${pkgs.bibata-cursors}/share/icons/Bibata-Modern-Classic";
      ".local/state/quickshell/.venv/bin/activate".text = ''
        # Generated by illogical-flake - provides the Nix Python env as a fake venv
        export VIRTUAL_ENV="${cfg.internal.pythonEnv}"
        export PATH="${cfg.internal.pythonEnv}/bin:$PATH"
        deactivate() { return 0; }
      '';
      ".local/state/quickshell/.venv/bin/python".source =
        "${cfg.internal.pythonEnv}/bin/python";
      ".local/state/quickshell/.venv/bin/python3".source =
        "${cfg.internal.pythonEnv}/bin/python3";
      ".local/state/quickshell/.venv/pyvenv.cfg".text = ''
        home = ${cfg.internal.pythonEnv}/bin
        include-system-site-packages = false
        version = 3.12.0
      '';
    };

    # Breeze icons are shipped via kdePackages.breeze-icons (see packages.nix)
    # so they're available to both Qt/KDE (Dolphin) and GTK apps.
    # Papirus themes are handled by activation script (to add inode-directory symlinks).

    # Symlink standard icon themes
    # Note: Papirus themes are handled by activation script (to add inode-directory symlinks)
    home.file.".local/share/icons/Adwaita".source = "${pkgs.adwaita-icon-theme}/share/icons/Adwaita";
    # hicolor and Papirus are managed by the activation script below, not as symlinks

    # Bookmarks for the GTK file chooser (both GTK3 and GTK4 native pickers).
    # Format: file:///path Label (one per line).
    home.file.".config/gtk-3.0/bookmarks".text = ''
      file://${config.home.homeDirectory}/Desktop Desktop
      file://${config.home.homeDirectory}/Documents Documents
      file://${config.home.homeDirectory}/Downloads Downloads
      file://${config.home.homeDirectory}/Pictures Pictures
      file://${config.home.homeDirectory}/Videos Videos
    '';
    home.file.".config/gtk-4.0/bookmarks".text = ''
      file://${config.home.homeDirectory}/Desktop Desktop
      file://${config.home.homeDirectory}/Documents Documents
      file://${config.home.homeDirectory}/Downloads Downloads
      file://${config.home.homeDirectory}/Pictures Pictures
      file://${config.home.homeDirectory}/Videos Videos
    '';

    # Configure icon theme for GTK and Qt applications
    # Use Breeze-Dark → same icon set as Dolphin/KDE apps (breeze icons
    # ship via kdePackages.breeze-icons, so both GTK and Qt see the same icons).
    gtk = {
      enable = mkDefault true;
      iconTheme = {
        name = mkDefault "breeze-dark";
        package = mkDefault pkgs.kdePackages.breeze-icons;
      };
    };

    # XDG user dirs (Desktop, Documents, Downloads, ...).
    # Firefox/Chromium и все портальные (GTK через xdg-desktop-portal-gtk)
    # пикеры файлов показывают закладки от сюда, а не из gtk bookmarks.
    xdg = {
      enable = mkDefault true;
      userDirs = {
        enable = mkDefault true;
        createDirectories = mkDefault true;
        desktop = mkDefault "$HOME/Desktop";
        documents = mkDefault "$HOME/Documents";
        download = mkDefault "$HOME/Downloads";
        music = mkDefault "$HOME/Music";
        pictures = mkDefault "$HOME/Pictures";
        projects = mkDefault null;
        publicShare = mkDefault "$HOME/.Public";
        templates = mkDefault "$HOME/.Templates";
        videos = mkDefault "$HOME/Videos";
      };
    };

    # Set icon theme via dconf for GNOME/GTK apps
    dconf.settings = {
      "org/gnome/desktop/interface" = {
        icon-theme = mkDefault "breeze-dark";
        cursor-theme = mkDefault "Bibata-Modern-Classic";
        cursor-size = mkDefault 24;
        # Base GTK theme that matugen's gtk.css layers colors on top of
        color-scheme = mkDefault "prefer-dark";
        gtk-theme = mkDefault "adw-gtk3";
      };
    };

    # Copy dotfiles into ~ (не symlink'ить!): QuickShell/wallpaper-пайплайн
    # ПИШЕТ в эти файлы в рантайме (kdeglobals, quickshell/generated, matugen),
    # а symlink на read-only store такую запись не переживёт. Поэтому cp -r при
    # каждом переключении — это бэкдор-механизм энд-4 окружения, и здесь он
    # остаётся по необходимости. Часть чистого контента (курсоры, bookmarks,
    # иконки) уже декларативна через home.file/dconf/gtk выше.
    home.activation.copyIllogicalImpulseConfigs = config.lib.dag.entryAfter ["writeBoundary"] ''
      configPath="${dotfilesSource}/.config"
      localShareSrc="${dotfilesSource}/.local/share"
      targetPath="$HOME/.config"
      targetLocalShare="$HOME/.local/share"

      # Каталоги, которыми QuickShell управляет динамически — не трогаем.
      excludedDirs=("illogical-impulse")
      # Файлы, которые принадлежат рантайму (wallpaper-пайплайн сливает в
      # kdeglobals материал-тему) — не затираем, если уже существуют.
      preserveFiles=("kdeglobals")

      # is_in <name> <items...>: есть ли name в списке.
      is_in() {
        local needle="$1"; shift
        for it in "$@"; do [ "$it" = "$needle" ] && return 0; done
        return 1
      }

      # Копируем $src/* в $dst БЕЗ symlink-ов, перезаписывая старые копии.
      # Доп. правила для .config: excluded (рантайм-каталоги) и preserved
      # (файлы, которые не должны затираться).
      copy_config() {
        $DRY_RUN_CMD mkdir -p "$targetPath"
        shopt -s nullglob
        for item in "$configPath"/*; do
          [ -e "$item" ] || continue
          name="$(basename "$item")"
          is_in "$name" "''${excludedDirs[@]}" && continue
          if is_in "$name" "''${preserveFiles[@]}" && [ -e "$targetPath/$name" ]; then
            continue
          fi
          if [ -e "$targetPath/$name" ] || [ -L "$targetPath/$name" ]; then
            $DRY_RUN_CMD rm -rf "$targetPath/$name"
          fi
          $DRY_RUN_CMD cp -r "$item" "$targetPath/$name"
          # Store-права read-only; рантайм должен мочь писать в копии.
          $DRY_RUN_CMD chmod -R u+w "$targetPath/$name"
        done
      }

      # То же для .local/share (иконки и т.п.), плюс перенос фирменной иконки
      # окружения в стандартный hicolor.
      copy_local_share() {
        $DRY_RUN_CMD mkdir -p "$targetLocalShare"
        shopt -s nullglob
        for item in "$localShareSrc"/*; do
          [ -e "$item" ] || continue
          name="$(basename "$item")"
          if [ -e "$targetLocalShare/$name" ] || [ -L "$targetLocalShare/$name" ]; then
            $DRY_RUN_CMD rm -rf "$targetLocalShare/$name"
          fi
          $DRY_RUN_CMD cp -r "$item" "$targetLocalShare/$name"
          $DRY_RUN_CMD chmod -R u+w "$targetLocalShare/$name"
        done
        if [ -f "$targetLocalShare/icons/illogical-impulse.svg" ]; then
          $DRY_RUN_CMD mkdir -p "$targetLocalShare/icons/hicolor/scalable/apps"
          $DRY_RUN_CMD mv "$targetLocalShare/icons/illogical-impulse.svg" "$targetLocalShare/icons/hicolor/scalable/apps/"
        fi
      }

      # --- .config: создаём каталог окружения + дефолтный config.json (только
      #     если его ещё нет — иначе сбрасывались бы пользовательские настройки).
      $DRY_RUN_CMD mkdir -p "$targetPath/illogical-impulse"
      if [ ! -f "$targetPath/illogical-impulse/config.json" ]; then
        if [ -f "$configPath/illogical-impulse/config.json" ]; then
          $DRY_RUN_CMD cp "$configPath/illogical-impulse/config.json" "$targetPath/illogical-impulse/config.json"
          $DRY_RUN_CMD chmod u+w "$targetPath/illogical-impulse/config.json"
        fi
      fi

      copy_config

      # --- Правки Qt-темирования после копирования (см. environment.nix) ---

      # (1) Иконки: Breeze. Qt/KDE читают kdeglobals (QT_QPA_PLATFORMTHEME=kde),
      #     единый источник правды — kdeglobals, а не qt5ct/qt6ct.
      icon_theme="breeze-dark"
      if [ "$(grep -q 'prefer-light' "$targetPath/gtk-3.0/settings.ini" 2>/dev/null && echo light)" = "light" ]; then
        icon_theme="breeze"
      fi
      if [ -f "$targetPath/kdeglobals" ]; then
        if $DRY_RUN_CMD grep -q '^\[Icons\]' "$targetPath/kdeglobals"; then
          $DRY_RUN_CMD sed -i "s/^Theme=.*/Theme=$icon_theme/" "$targetPath/kdeglobals"
        else
          printf '\n[Icons]\nTheme=%s\n' "$icon_theme" >> "$targetPath/kdeglobals"
        fi
        echo "Set kdeglobals icon theme to $icon_theme"
      fi

      # (2) Шрифты: upstream ссылается на "Google Sans Flex", которого нет
      #     (fc-match падает на DejaVu). Используем Rubik (стоит, используется shell).
      for entry in "font=Google Sans Flex,11,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Medium" \
                   "menuFont=Google Sans Flex,10,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Medium" \
                   "smallestReadableFont=Google Sans Flex,9,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Medium" \
                   "toolBarFont=Google Sans Flex,10,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Medium" \
                   "activeFont=Google Sans Flex,10,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Medium"; do
        key="''${entry%%=*}"
        $DRY_RUN_CMD sed -i "/^''${key}=/s|Google Sans Flex,''${key#font}|Rubik,''${key#font}|; /^''${key}=/s|Google Sans Flex|Rubik|g" "$targetPath/kdeglobals"
      done
      echo "Fixed kdeglobals fonts (Google Sans Flex -> Rubik)"

      # (3) Снос устаревших qt5ct/qt6ct конфигов от старых версий flake —
      #     они теперь мертвы и путают диалоги настроек Qt.
      $DRY_RUN_CMD rm -rf "$targetPath/qt5ct" "$targetPath/qt6ct"

      # (4) fontconfig/conf.d должен быть директорией, а не файлом.
      if [ -f "$targetPath/fontconfig/conf.d" ]; then
        $DRY_RUN_CMD rm "$targetPath/fontconfig/conf.d"
        $DRY_RUN_CMD mkdir -p "$targetPath/fontconfig/conf.d"
      fi

      # --- .local/share ---
      copy_local_share

      # Удаляем устаревшие OneUI-темы от старых установок.
      for stale_theme in OneUI OneUI-dark OneUI-light; do
        if [ -e "$targetLocalShare/icons/$stale_theme" ] || [ -L "$targetLocalShare/icons/$stale_theme" ]; then
          $DRY_RUN_CMD rm -rf "$targetLocalShare/icons/$stale_theme"
          echo "Removed stale $stale_theme icon theme"
        fi
      done

      # Papirus: темы приходят уже с исправленным наследованием (Adwaita вместо
      # breeze — breeze не содержит inode-directory иконок) из pkgs/default.nix,
      # патч делается при СБОРКЕ пакета. Здесь осталось только скопировать их
      # локально (GTK/quickshell смотрят в ~/.local/share/icons).
      echo "Installing Papirus icon themes..."
      for theme in Papirus Papirus-Dark Papirus-Light; do
        local_theme="$targetLocalShare/icons/$theme"
        source_theme="${customPkgs.papirus-patched}/share/icons/$theme"
        if [ -e "$local_theme" ] || [ -L "$local_theme" ]; then
          $DRY_RUN_CMD rm -rf "$local_theme"
        fi
        if [ -d "$source_theme" ]; then
          $DRY_RUN_CMD cp -r "$source_theme" "$local_theme"
          $DRY_RUN_CMD chmod -R u+w "$local_theme"
        fi
      done

      # Обновляем кэш иконок для всех установленных тем.
      echo "Updating icon cache..."
      shopt -s nullglob
      for theme_dir in "$targetLocalShare/icons"/*; do
        [ -d "$theme_dir" ] || continue
        if [ -e "$theme_dir/index.theme" ] || [ -e "$theme_dir/icon-theme.cache" ]; then
          $DRY_RUN_CMD ${pkgs.gtk3}/bin/gtk-update-icon-cache -f -t "$theme_dir" 2>/dev/null || true
        fi
      done
    '';
  };
}